# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.empty((3,3,3))

array([[[3.56043053e-307, 1.60219306e-306, 7.56571288e-307],
        [1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307]],

       [[1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
        [1.33511018e-306, 6.23057689e-307, 1.86921279e-306],
        [8.90098127e-307, 1.78020848e-306, 1.60219035e-306]],

       [[1.42418172e-306, 2.04712906e-306, 7.56589622e-307],
        [1.11258277e-307, 8.90111708e-307, 2.11389826e-307],
        [1.11260619e-306, 1.11253693e-306, 3.39980405e-317]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
import numpy as np
d=np.diag(1+np.arange(4),k=-1)
print(d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.73953411 0.06712215 0.04498128 0.01463287 0.52059584]
 [0.26924704 0.4377329  0.65186784 0.92368761 0.27768876]
 [0.91695908 0.05976406 0.42377732 0.17554827 0.97040101]
 [0.01814567 0.02379347 0.2342002  0.72230506 0.7789557 ]
 [0.87680538 0.90608697 0.10246578 0.05745602 0.23108277]]
After normalization:
[[0.75844885 0.05491842 0.0317529  0.         0.52937836]
 [0.26639742 0.44268062 0.66672548 0.95112476 0.27522981]
 [0.94408484 0.04721981 0.42807919 0.16836238 1.        ]
 [0.00367537 0.00958454 0.22972865 0.74042245 0.79969482]
 [0.90207287 0.93270958 0.09189771 0.04480496 0.22646695]]


# 5.  How to find common values between two arrays?

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

# 6.How to get the dates of yesterday, today and tomorrow?

In [5]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-24
Today :  2020-07-25
Tomorrow :  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [18]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 1 1]
Second array:
[0 0 1 1 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [19]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 10
print(x)

Original array:
[0.81240588 0.75781809 0.69854958 0.59418891 0.1694596  0.50506252
 0.63368865 0.26098143 0.43295583 0.54267   ]
[10.          0.75781809  0.69854958  0.59418891  0.1694596   0.50506252
  0.63368865  0.26098143  0.43295583  0.54267   ]


# 9. How to print all the values of an array?

In [3]:
y=np.random.random(20)
np.set_printoptions()
y

array([0.94612871, 0.02917087, 0.49731998, 0.77642988, 0.23203523,
       0.29830545, 0.89481584, 0.6059312 , 0.23997376, 0.95031577,
       0.99563973, 0.82275244, 0.51733951, 0.28508628, 0.92825056,
       0.87536838, 0.00834775, 0.64714487, 0.78971638, 0.71454513])

# 10.Subtract the mean of each row of a matrix

In [2]:
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.71356172 0.93115587 0.09340201]
 [0.19027967 0.26072287 0.19867103]
 [0.10306722 0.42967661 0.83060139]]

Subtract the mean of each row of the said matrix:

[[ 0.13418852  0.35178267 -0.48597119]
 [-0.02627819  0.04416501 -0.01788683]
 [-0.35138119 -0.0247718   0.37615299]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [8]:
N=np.ones(10)
I=np.random.randint(0,len(N),20)
N+=np.bincount(I,minlength=len(N))
print(N)

[1. 5. 4. 4. 2. 2. 1. 4. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [7]:
A = np.array([[1,3,4],[8,7,3]])
B = np.array([[5,3],[2,4],[1,7]])
print("After dot product: ",np.dot(A,B))
print(np.diag(np.dot(A,B)))

After dot product:  [[15 43]
 [57 73]]
[15 73]


# 13.How to find the most frequent value in an array?

In [3]:
import numpy as np
x = np.random.randint(0, 10,20 )
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[9 5 5 5 0 5 1 8 7 4 9 2 6 8 7 8 6 9 4 5]
Most frequent value in the above array:
5


# 14.How to get the n largest values of an array

In [6]:

import numpy as np
N = int(input("Enter the length of the array"))
x = np.arange(N)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Enter the length of the array16
Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[15]


# 15.How to create a record array from a regular array?

In [22]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S10, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin ', 88.5, 90) (b'Ayaana M', 87. , 99) (b'Jody Pre', 85.5, 91)]
